name: Update LeetCode Progress

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Run progress script
        run: python scripts/update_progress.py

      - name: Commit README
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Auto update progress" || echo "No changes"
          git push
